nombre = input("Ingresa el nombre:")
print(nombre)
edad = int(input("Ingresa la edad:"))
print(edad)
peso = float(input("Ingresa el peso:"))
print(peso)
numero_1 = int(input("Ingrese el 1er numero:"))
numero_2 = int(input("Ingrese el 2do numero:"))
print("El resultado de la suma es:", numero_1+numero_2)